/**
 * Period names chosen by hand for provinces the pipeline named after modern admin regions, where
 * the names that `npm run mapgen:names` finds in Natural Earth would be wrong or out of their time:
 * rivers, towns and lands as they were known in the eleventh century where that is known. Keyed by
 * the province's name in the map data.
 */
export const PERIOD_NAMES: Record<string, string> = {
  // Iberia and France
  'East Badajoz': 'Medellín',
  'East Ciudad Real': 'Calatrava',
  'West Cáceres': 'Alcántara',
  'North-East Santander': 'Santillana',
  'West Brest': 'Léon',
  // Eastern Europe and the steppe
  'North Minsk': 'Iziaslavl',
  'South-East Lublin': 'Czerwień',
  'South-East Odessa': 'Budjak',
  'South-West Kherson': 'Oleshye',
  'West Poltava': 'Ltava',
  'North-West Kharkiv': 'Vorskla',
  'East Kursk': 'Seym',
  'East Pskov': 'Lovat',
  'South Novgorod': 'Russa',
  'West Vologda': 'Beloozero',
  'East Vologda': 'Sukhona',
  'West Kostroma': 'Merya',
  'South-East Nizhny Novgorod': 'Sura',
  'South Voronezh': 'Upper Don',
  'East Voronezh': 'Bityug',
  'East Saratov': 'Irgiz',
  'North Volgograd': 'Medveditsa',
  'South-East Volgograd': 'Akhtuba',
  'South Rostov': 'Mius',
  'South-East Rostov': 'Lower Donets',
  'South-East Rostov II': 'Sal',
  'West Republic of Kalmykia': 'Manych',
  'North-East Republic of Kalmykia': 'Sarpa',
  // The Urals, Siberia and the Kipchak steppe
  'North Sverdlovsk': 'Pelym',
  'South Sverdlovsk': 'Lower Iset',
  'South Chelyabinsk': 'Uy Steppe',
  'North-West Altai': 'Baraba Steppe',
  'South-West Novosibirsk': 'Kulunda Steppe',
  'West Atyrau': 'Ryn Sands',
  'West Kazakhstan': 'Uzen',
  'North-West Aktobe': 'Ilek',
  'North-East Aktobe': 'Mugodzhar',
  'South-West Aktobe': 'Emba',
  'South-East Karaganda': 'Betpak-Dala',
  'North-East Karaganda': 'Nura',
  'East North Kazakhstan': 'Selety',
  'South-East Pavlodar': 'Bayanaul',
  'West Kostanay': 'Upper Tobol',
  'North-East Pavlodar': 'Upper Irtysh',
  'South Omsk': 'Middle Irtysh',
  'North-East Tyumen': 'Lower Irtysh',
  'North-West Almaty': 'Ili',
  'South Karakalpakstan': 'Ustyurt',
  // Arabia, Persia and the Indus
  'East Tabuk': 'Tayma',
  'North Al Madinah': 'Khaybar',
  'North-West Al Madinah': 'Al-Ula',
  'South-East Al Madinah': 'Mahd adh-Dhahab',
  'North-West Makkah': 'Khurma',
  'North Eastern': 'Jafura',
  'South Kerman': 'Minab',
  'North-East Balochistan': 'Sibi',
  'South-East Balochistan II': 'Kirthar Hills',
  'East Sivas': 'Koloneia',
  // India and China
  'North Madhya Pradesh': 'Jejakabhukti',
  'North-West Madhya Pradesh II': 'Braj',
  'South-West Chhattisgarh': 'Mahanadi',
  'South Yulin': 'Hepu',
  'East Sichuan': 'Guozhou',
  'South-East Hunan': 'Hengzhou',
  'North-West Jilin': 'Upper Songhua',
  // Africa and the Americas
  'West Suss-Massa-Draa': 'Draa',
  'East Darfur': 'Daju',
  'South Kordofan': 'Nuba Mountains',
  'North Al Qadarif': 'Butana',
  'South-East Al Qadarif': 'Gallabat',
  'South-East Sennar': 'Fazughli',
  'West Sennar': 'Gezira',
  'North-East Kassala': 'Taka',
  'North-West Veracruz': 'Huasteca',
  'South North Darfur': 'Wadi Howar',
  'North-West South Kordofan': 'Abu Habl',
  'North-West South Khorasan': 'Quhistan',
  'East West Kazakhstan': 'Yaik',
  'West South Sumatra': 'Upper Musi',
  // Australia, by its rivers, rocks and peoples
  'North-West Western Australia': 'Pilbara',
  'North-West Western Australia II': 'Ashburton',
  'West Western Australia II': 'Gascoyne',
  'West Western Australia': 'Murchison',
  'South-West Western Australia': 'Moore',
  'South Western Australia': 'Karlkurla',
  'South Western Australia II': 'Ngadju',
  'South-East Northern III': 'Uluru',
  // Modern admin regions named whole
  'Republic of Kalmykia': 'Yergeni',
  'North Kazakhstan': 'Kokshetau Hills',
  'East Kazakhstan': 'Chingiz-Tau',
  'West Bengal': 'Varendra',
  'West Macedonia': 'Kastoria',
  'South Sumatra': 'Lower Musi',
  'North Sumatra': 'Barus',
  'Central Kalimantan': 'Kahayan',
  'East Kalimantan': 'Berau',
  'West Kalimantan': 'Kapuas',
  'South Kalimantan': 'Banjar',
  'Central Sulawesi': 'Tomini',
  'West Papua': 'Bomberai',
};
