/**
 * Extracts the handful of game-icons.net glyphs the game uses (heraldic charges and UI icons) from
 * @iconify-json/game-icons into src/assets/icons.ts, so the 6 MB collection never ships.
 * Icons by Lorc, Delapouite and contributors, https://game-icons.net, CC BY 3.0.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const file = require.resolve('@iconify-json/game-icons/icons.json');
const data = JSON.parse(readFileSync(file, 'utf8')) as { icons: Record<string, { body: string }> };

export const HERALDIC = [
  'lion',
  'eagle-emblem',
  'hawk-emblem',
  'fleur-de-lys',
  'stone-tower',
  'castle',
  'key',
  'trident',
  'crown',
  'imperial-crown',
  'heraldic-sun',
  'moon',
  'crossed-swords',
  'wyvern',
  'dragon-head',
  'boar',
  'deer',
  'bear-head',
  'wolf-head',
  'griffin-symbol',
  'unicorn',
  'bull',
  'raven',
  'dove',
  'lotus',
  'rose',
  'horse-head',
  'camel',
  'elephant',
  'tiger-head',
  'pope-crown',
  'anchor',
  'flower-emblem',
  'yin-yang',
  'pagoda',
  'ankh',
];
const UI = [
  'coins',
  'two-coins',
  'swordman',
  'mounted-knight',
  'black-knight-helm',
  'meeple-group',
  'meeple-king',
  'prayer',
  'scroll-unfurled',
  'quill-ink',
  'scales',
  'star-medal',
  'hourglass',
  'pause-button',
  'play-button',
  'fast-forward-button',
  'magnifying-glass',
  'save',
  'hamburger-menu',
  'cog',
  'family-house',
  'village',
  'wheat',
  'hill-fort',
  'military-fort',
  'defensive-wall',
  'siege-tower',
  'barracks-tent',
  'open-treasure-chest',
  'money-stack',
  'contract',
  'wax-seal',
  'globe',
  'compass',
  'spyglass',
  'cloak-dagger',
  'hooded-assassin',
  'crowned-heart',
  'throne-king',
  'church',
  'samara-mosque',
  'byzantin-temple',
  'open-book',
  'anvil',
  'ship-wheel',
  'sands-of-time',
  'podium-winner',
  'treasure-map',
  'all-seeing-eye',
  'cross-mark',
  'mountains',
  'pine-tree',
];

const out: Record<string, string> = {};
for (const name of [...new Set([...HERALDIC, ...UI])]) {
  const icon = data.icons[name];
  if (!icon) throw new Error(`Icon ${name} not found`);
  out[name] = icon.body.replace(/\s*fill="currentColor"/g, '');
}
const header = `/* Generated by tools/icons/extract.ts — do not edit.
 * Icons from game-icons.net by Lorc, Delapouite and contributors, licensed CC BY 3.0
 * (https://creativecommons.org/licenses/by/3.0/). All icons use a 512×512 viewBox. */
`;
writeFileSync(
  'src/assets/icons.ts',
  `${header}export type IconName = ${Object.keys(out)
    .map((n) => `'${n}'`)
    .join(' | ')};\n\nexport const ICONS: Record<IconName, string> = ${JSON.stringify(out, null, 1)};\n`,
);
console.log(`Wrote ${Object.keys(out).length} icons`);
